name: Build app
description: Test, build and pack app artifacts

runs:
  using: composite
  steps:

    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Install mage tool
      run: |
        go install github.com/magefile/mage
      shell: bash

    - name: Run the build
      run: |
        mage
      shell: bash

    - name: Zip the compiled file
      run: |
        zip tf-plan-reporter_linux_amd64.zip tf-plan-reporter
      shell: bash
