name: Check current PR

on:
  pull_request:
    types:
    - labeled
    - unlabeled
    - opened
    - synchronize
    - edited
  workflow_call:

jobs:
  validate_current_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: current-pull-request-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true
          filterOutDraft: false

      - name: Check if the Pull Request has been labeled
        if: steps.current-pull-request-info.outcome == 'success'
        run: |
          threshold=1
          if (( `echo -n "${{ steps.current-pull-request-info.outputs.pr_labels }}" | tr "," " " | wc -m` < $threshold )); then
            echo "::error::The pull request must contain at least $threshold labels"
            exit 1
          fi

      - name: Check if the Pull Request has not empty description
        if: steps.current-pull-request-info.outcome == 'success'
        run: |
          output_file="current-pull-request-info_description"
          cat << \EOF >$output_file
          ${{ steps.current-pull-request-info.outputs.pr_body }}
          EOF

          threshold=30
          if (( `cat $output_file | wc -m` <  $threshold )); then
            echo "::error::The pull request description must contain at least $threshold characters"
            exit 1
          fi

      - name: Find dependent Pull Request
        uses: juliangruber/find-pull-request-action@v1
        if: github.base_ref == 'master'
        id: find-pull-request
        with:
          base: ${{ github.head_ref }}
          state: open

      - name: Block the Pull Request merge if there is existing Pull Request to target branch "${{ github.head_ref }}"
        if: steps.find-pull-request.outcome == 'success'
        run: |
          if [[ '${{ steps.find-pull-request.outputs.number }}' != '' ]]; then
            echo "::error::There is at least 1 Pull Request #${{ steps.find-pull-request.outputs.number }} that MUST be merged before the current one"
            exit 1
          fi
